### ISSUE TITLE
[bug] You can't import a danger zone scene data

### ISSUE THREAD

**Issue by brunocalado** [napolitanod/Danger-Zone#12]
If you try to import a scene you'll get an error. 

You can't also use danger zone in that scene.

error
![image](https://user-images.githubusercontent.com/4999783/135097628-ee798890-39c9-4ad6-9e17-8553f60a7811.png)

scene
[fvtt-Scene-hyperspace-mp4 - Copia.txt](https://github.com/napolitanod/Danger-Zone/files/7244434/fvtt-Scene-hyperspace-mp4.-.Copia.txt)

**Comment by napolitanod** [comment]
Thank you for reporting this - appears to be a couple of issues with importing scenes and the handling of the Danger Zone ids. I'll get a fix out for this.

**Comment by napolitanod** [comment]
I think I have fixed this with the latest release (0.0.9). On next update of this module you should be able to import scenes without error. If you already have a scene imported that experienced these errors, you should be able to edit that scene (i.e. configure) and then just save it and that should convert the zones that are in error to be functional again for that scene.

Note that if the world doesn't have the dangers in them that are on the scene being imported (or if the dangers on that scene were not imported also from the other world that the scene was previously exported from so that they share the same id) then you will still be able to import the scene without error, the zones will still show in the scene configure form, but they won't have a danger associated to them anymore.

please let me know if this addresses the error you were seeing.

Thanks!

**Comment by brunocalado** [comment]
worked. tks
