### ISSUE TITLE
Translate French

### ISSUE THREAD

**Issue by Elfenduil** [napolitanod/Danger-Zone#27]
Hello,

Can you add the French translation in the module, see file in Att ?

Thank you
[Traduction Fr.txt](https://github.com/napolitanod/Danger-Zone/files/7561535/Traduction.Fr.txt)

**Comment by napolitanod** [comment]
Cool! With the switch in languages I am seeing some bad css choices I made in the forms. Once I clean those up I'll add the French translation!

Thanks!

**Comment by napolitanod** [comment]
Okay - this is live with 0.8.1

I reworked some CSS to fit the text better and updated the file you provided me slightly to move (s) and (ms) into placeholders within the actual input box.

In some cases the translation runs long so those are shown as truncated with ellipses in order to fit the line - these are not truncated in the actual fr.json though. If there are any translations that are not understandable in truncated form that you have an abbreviation for please send the updates and I'll get those into the next release.

Thanks again!
