### ISSUE TITLE
dangers not doing damage with latest versions of midi-qol

### ISSUE THREAD

**Issue by KammaKhazi** [napolitanod/Danger-Zone#56]
Heya, I've just been doing some testing at it seems with the latest version of Midi-QOL (v0.9.42) that dangers I had set up (that were working perfectly prior) have stopped doing damage to tokens. I noticed Tim has been doing something with the damage only workflow in his changelog. kind regards.

**Comment by napolitanod** [comment]
Thank you for the report. I had an open bug reported for an issue introduced a little over  a week ago with the damage only workflow that looks like they fixed in .42 but it does still overall seem to be not working. Looks like there was another issue further into the process that is now being hit after .42 cleared the first.

If you know your way around modules folder in foundry data the fix is to add the ? as shown in the bold below in what was previously charName: workflow.actor.name. This is in the midiQol src > module folder in the utils.js file line 500.

I'll open another issue with midiQol to see if this is something that can be addressed.

```js
	if (theTargets.size > 0) {
		await timedAwaitExecuteAsGM("createReverseDamageCard", {
			autoApplyDamage: configSettings.autoApplyDamage,
			sender: game.user?.name,
			charName: workflow.actor?.name,
			damageList: damageList,
			targetNames,
			chatCardId: workflow.itemCardId,
			flagTags: workflow?.flagTags
		});
```

**Comment by KammaKhazi** [comment]
ok cheers, will hold out for Tim's fix sure it will get sorted.

**Comment by KammaKhazi** [comment]
I've just tested this in Midi 0.9.43, looks like it was fixed =)
