### ISSUE TITLE
I can't make the danger show in the scene

### ISSUE THREAD

**Issue by brunocalado** [napolitanod/Danger-Zone#9]
Hi. Great job with this module.

But, I'm having trouble to use it. Can you add to the module a pre-made example?

I can't get this to show. I already created a danger.
![image](https://user-images.githubusercontent.com/4999783/134934204-ae0a1c58-ae8d-4523-948f-a5bbbe64ea22.png)

**Comment by napolitanod** [comment]
Hello!

Thank you for using the module. If I understand correctly, when you open the scene configuration form (as in the example screenshot that you provided), you are not seeing a Danger Zone section between the 'Weather Effect' and the 'Initial View Position'? 

Is the scene grid-type gridless? If it is, then this section will not show. I haven't yet extended this module to include gridless scenes due to how much more complex that math can get. If this is the issue, please try on a scene with a grid option selected (you'll need to save the scene configuration form if changing from gridless to grid in order for the section to show). 

The wiki includes a couple examples right now and I will add more once the module is out of beta (due to how the form layouts may change and make screenshot obsolete). Here is one example: https://github.com/napolitanod/Danger-Zone/wiki/Example:-Healing-Glade 

But if you aren't seeing the Danger Zone section in the scene configuration form and it is a gridded map, that is some other issue. Please let me know if that is the case (and if it is the case with other modules disabled) and we can troubleshoot from there. In your response, please let me know what system you are using (e.g. dnd5e) in case it is one that has some sort of customization on the scene form that may be interfering here.

Thank you!

**Comment by brunocalado** [comment]
Turn on the grid make it work. Tks

**Comment by napolitanod** [comment]
updated github readme to include that gridless maps currently not supported.

thanks!
